import type { Metadata } from "next";
import { Alata } from "next/font/google";
import "./globals.css";
import { Navbar } from "@/components/navbar/Navbar";
import Footer from "@/components/footer/Footer";
import { CartProvider } from "@/components/context/CartProvider";
import { UseAuth } from "@/components/context/UseAuth";
import { Toaster } from "sonner";

const alata = Alata({
  weight: "400",
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "F Tech",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={alata.className}>
        <Toaster richColors />
        <CartProvider>
          <UseAuth>
            <Navbar />
            {children}
            <Footer />
          </UseAuth>
        </CartProvider>
      </body>
    </html>
  );
}
